#!/usr/bin/env python3
"""
Generate a repo-local data lineage doc for FinSkills (China-market).

Inputs (generated by tools/generate_data_queries_docs.py):
- docs/view-deps.json
- docs/view-specs/*.json

Output:
- docs/data-lineage.md
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable


REPO_ROOT = Path(__file__).resolve().parents[1]
DOCS_DIR = REPO_ROOT / "docs"
VIEW_DEPS = DOCS_DIR / "view-deps.json"
VIEW_SPECS_DIR = DOCS_DIR / "view-specs"
OUT_MD = DOCS_DIR / "data-lineage.md"


def _read_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def _slug(s: str) -> str:
    return re.sub(r"[^a-zA-Z0-9_]+", "_", (s or "").strip())


def _dedup(seq: Iterable[str]) -> list[str]:
    seen: set[str] = set()
    out: list[str] = []
    for x in seq:
        if not x or x in seen:
            continue
        seen.add(x)
        out.append(x)
    return out


@dataclass(frozen=True)
class Primitive:
    key: str
    label: str
    providers: list[str]  # conceptual providers; may map to akshare-one sources
    patterns: list[re.Pattern]


PRIMITIVES: list[Primitive] = [
    Primitive(
        key="pv_hist_ohlcv",
        label="PV.HistOHLCV (A股/港股历史行情)",
        providers=["eastmoney", "eastmoney_direct", "sina"],
        patterns=[re.compile(r"^stock_zh_a_hist$")],
    ),
    Primitive(
        key="pv_realtime_quotes",
        label="PV.RealtimeQuotes (实时行情/盘口)",
        providers=["eastmoney", "eastmoney_direct", "xueqiu"],
        patterns=[
            re.compile(r"^stock_zh_a_spot_em$"),
            re.compile(r"^stock_bj_a_spot_em$"),
            re.compile(r"^stock_intraday_em$"),
            re.compile(r"^stock_bid_ask_em$"),
        ],
    ),
    Primitive(
        key="pv_basic_info",
        label="PV.BasicInfo (基础信息/行业/上市日期等)",
        providers=["eastmoney"],
        patterns=[re.compile(r"^stock_individual_info_em$"), re.compile(r"^stock_info_bj_name_code$")],
    ),
    Primitive(
        key="pv_news_disclosure",
        label="PV.DisclosureNews (公告/信披/交易提示)",
        providers=["eastmoney"],  # akshare-one: stock news only eastmoney; disclosures here are broader (AKShare site-level).
        patterns=[
            re.compile(r"^stock_notice_report$"),
            re.compile(r"^stock_report_disclosure$"),
            re.compile(r"^stock_repurchase_em$"),
            re.compile(r"^stock_share_change_cninfo$"),
            re.compile(r"^cninfo_"),
            re.compile(r"^notice_"),
            re.compile(r"^report_disclosure_"),
            re.compile(r"^news_trade_notify_"),
        ],
    ),
    Primitive(
        key="pv_block_deal",
        label="PV.BlockDeal (大宗交易)",
        providers=["eastmoney"],
        patterns=[re.compile(r"^stock_dzjy_")],
    ),
    Primitive(
        key="pv_fin_statements",
        label="PV.FinStatements (三大报表)",
        providers=["eastmoney", "sina"],
        patterns=[
            re.compile(r"^stock_balance_sheet_by_report_em$"),
            re.compile(r"^stock_profit_sheet_by_report_em$"),
            re.compile(r"^stock_cash_flow_sheet_by_report_em$"),
            re.compile(r"^stock_zcfz_bj_em$"),
        ],
    ),
    Primitive(
        key="pv_fin_metrics",
        label="PV.FinMetrics (关键财务指标/估值/质量)",
        providers=["eastmoney_direct", "sina"],
        patterns=[
            re.compile(r"^stock_financial_abstract_ths$"),
            re.compile(r"^stock_financial_analysis_indicator$"),
            re.compile(r"^stock_a_indicator_lg$"),
            re.compile(r"^stock_buffett_index_lg$"),
            re.compile(r"^stock_index_pe_lg$"),
            re.compile(r"^stock_index_pb_lg$"),
        ],
    ),
    Primitive(
        key="pv_insider_mgmt",
        label="PV.InsiderMgmt (内部交易/高管增减持)",
        providers=["xueqiu", "eastmoney_direct"],
        patterns=[re.compile(r"^stock_inner_trade_xq$"), re.compile(r"^stock_ggcg_em$")],
    ),
    Primitive(
        key="pv_macro_cn",
        label="PV.MacroCN (LPR/PMI/CPI/M2/Shibor/社融)",
        providers=["akshare-macro (site-specific)"],
        patterns=[re.compile(r"^macro_"), re.compile(r"^rate_interbank$")],
    ),
    Primitive(
        key="pv_fundflow",
        label="PV.FundFlow (资金流/主力/板块)",
        providers=["akshare-fundflow (site-specific)"],
        patterns=[re.compile(r"^stock_.*fund_flow"), re.compile(r"^stock_market_fund_flow$"), re.compile(r"^stock_main_fund_flow$")],
    ),
    Primitive(
        key="pv_northbound",
        label="PV.NorthboundHSGT (沪深港通/北向)",
        providers=["akshare-hsgt (site-specific)"],
        patterns=[re.compile(r"^stock_hsgt_")],
    ),
    Primitive(
        key="pv_lhb",
        label="PV.DragonTigerLHB (龙虎榜)",
        providers=["akshare-lhb (site-specific)"],
        patterns=[re.compile(r"^stock_lhb_")],
    ),
    Primitive(
        key="pv_zt_pool",
        label="PV.LimitUpDown (涨停池/强势股池)",
        providers=["akshare-zt (site-specific)"],
        patterns=[re.compile(r"^stock_zt_pool_")],
    ),
    Primitive(
        key="pv_margin",
        label="PV.MarginFinancing (融资融券)",
        providers=["akshare-margin (site-specific)"],
        patterns=[re.compile(r"^stock_margin_")],
    ),
    Primitive(
        key="pv_pledge",
        label="PV.EquityPledge (股权质押)",
        providers=["akshare-gpzy (site-specific)"],
        patterns=[re.compile(r"^stock_gpzy_")],
    ),
    Primitive(
        key="pv_restricted",
        label="PV.RestrictedRelease (限售解禁)",
        providers=["akshare-restricted (site-specific)"],
        patterns=[re.compile(r"^stock_restricted_release_")],
    ),
    Primitive(
        key="pv_goodwill",
        label="PV.Goodwill (商誉/减值)",
        providers=["akshare-sy (site-specific)"],
        patterns=[re.compile(r"^stock_sy_")],
    ),
    Primitive(
        key="pv_esg",
        label="PV.ESG (ESG评分/等级)",
        providers=["akshare-esg (site-specific)"],
        patterns=[re.compile(r"^stock_esg_")],
    ),
]


FEATURE_VIEWS = {
    "macro_china_dashboard": "Macro Dashboard",
    "market_overview_dashboard": "Market Overview Dashboard",
    "fund_flow_dashboard": "Fund Flow Dashboard",
    "hsgt_dashboard": "HSGT Dashboard",
    "dragon_tiger_daily": "Dragon-Tiger Daily",
    "dragon_tiger_stock_detail": "Dragon-Tiger Stock Detail",
    "limit_up_pool_daily": "Limit-Up Pool Daily",
    "equity_pledge_dashboard": "Equity Pledge Dashboard",
    "margin_dashboard": "Margin Dashboard",
    "block_deal_dashboard": "Block Deal Dashboard",
    "repurchase_dashboard": "Repurchase Dashboard",
    "restricted_release_dashboard": "Restricted Release Dashboard",
    "goodwill_dashboard": "Goodwill Dashboard",
    "dividend_actions_dashboard": "Dividend Actions Dashboard",
    "notice_daily_dashboard": "Notice Daily Dashboard",
    "report_disclosure_calendar": "Disclosure Calendar",
    "cninfo_disclosure_search": "CNINFO Search",
    "cninfo_disclosure_relation_search": "CNINFO Relation Search",
    "concept_board_snapshot": "Concept Board Snapshot",
    "concept_board_detail": "Concept Board Detail",
    "industry_board_snapshot": "Industry Board Snapshot",
    "industry_board_detail": "Industry Board Detail",
    "hot_rank_sentiment_dashboard": "Hot Rank / Sentiment Dashboard",
    "ipo_newlist_dashboard": "IPO Newlist Dashboard",
    "shareholder_structure_dashboard": "Shareholder Structure Dashboard",
    "st_delist_dashboard": "ST/Delist Dashboard",
    "intraday_microstructure_dashboard": "Intraday Microstructure Dashboard",
    "ab_ah_premium_dashboard": "AB/AH Premium Dashboard",
}


def _classify_primitives(tool_views: Iterable[str]) -> list[Primitive]:
    found: list[Primitive] = []
    tv = list(tool_views)
    for p in PRIMITIVES:
        if any(any(pat.match(x) for pat in p.patterns) for x in tv):
            found.append(p)
    return found


def main() -> int:
    deps = _read_json(VIEW_DEPS)
    china: dict[str, dict[str, Any]] = deps.get("china") or {}

    # Load view specs for expanding custom views.
    view_specs: dict[str, dict[str, Any]] = {}
    if VIEW_SPECS_DIR.exists():
        for p in VIEW_SPECS_DIR.glob("*.json"):
            if p.name == "index.json":
                continue
            view_specs[p.stem] = _read_json(p)

    # Build per-skill expanded tool view set + feature view set.
    per_skill_tool_views: dict[str, list[str]] = {}
    per_skill_feature_views: dict[str, list[str]] = {}

    for skill, spec in sorted(china.items()):
        views = spec.get("views") or []
        features = []
        tools = []
        for v in views:
            vs = view_specs.get(v)
            if vs and vs.get("kind") == "custom_view":
                features.append(v)
                tools.extend(vs.get("depends_on") or [])
            else:
                tools.append(v)
        per_skill_tool_views[skill] = _dedup(tools)
        per_skill_feature_views[skill] = _dedup([f for f in features if f in FEATURE_VIEWS])

    # Primitive -> impacted skills
    primitive_to_skills: dict[str, list[str]] = {}
    for p in PRIMITIVES:
        impacted = []
        for skill, tools in per_skill_tool_views.items():
            if any(any(pat.match(t) for pat in p.patterns) for t in tools):
                impacted.append(skill)
        primitive_to_skills[p.key] = impacted

    # Mermaid diagram (high-level)
    providers_nodes = {
        "eastmoney": "EastMoney",
        "eastmoney_direct": "EastMoney Direct",
        "sina": "Sina",
        "xueqiu": "Xueqiu",
        "akshare-macro (site-specific)": "Macro Sites (AKShare)",
        "akshare-fundflow (site-specific)": "FundFlow Sites (AKShare)",
        "akshare-hsgt (site-specific)": "HSGT Sites (AKShare)",
        "akshare-lhb (site-specific)": "LHB Sites (AKShare)",
        "akshare-zt (site-specific)": "ZT Pool Sites (AKShare)",
        "akshare-margin (site-specific)": "Margin Sites (AKShare)",
        "akshare-gpzy (site-specific)": "Pledge Sites (AKShare)",
        "akshare-restricted (site-specific)": "Restricted Sites (AKShare)",
        "akshare-sy (site-specific)": "Goodwill Sites (AKShare)",
        "akshare-esg (site-specific)": "ESG Sites (AKShare)",
    }

    def pv_node(p: Primitive) -> str:
        return _slug(p.key)

    m = []
    m.append("```mermaid")
    m.append("flowchart LR")
    m.append("  classDef provider fill:#eef,stroke:#66f,stroke-width:1px;")
    m.append("  classDef primitive fill:#efe,stroke:#393,stroke-width:1px;")
    m.append("  classDef feature fill:#ffe,stroke:#aa0,stroke-width:1px;")
    m.append("  classDef skill fill:#fef,stroke:#909,stroke-width:1px;")
    m.append("")
    m.append("  subgraph Providers")
    for k, label in providers_nodes.items():
        m.append(f'    {_slug(k)}["{label}"]:::provider')
    m.append("  end")
    m.append("")
    m.append("  subgraph PrimitiveViews")
    for p in PRIMITIVES:
        m.append(f'    {pv_node(p)}["{p.label}"]:::primitive')
    m.append("  end")
    m.append("")
    for p in PRIMITIVES:
        for prov in p.providers:
            m.append(f"  {_slug(prov)} --> {pv_node(p)}")
    m.append("")
    m.append("  subgraph FeatureViews")
    # Keep the feature layer compact: only the named custom views
    for fv, label in FEATURE_VIEWS.items():
        m.append(f'    {_slug(fv)}["{label}"]:::feature')
    m.append("  end")
    m.append("")
    # Feature -> primitive edges via depends_on patterns (approx)
    for fv, label in FEATURE_VIEWS.items():
        vs = view_specs.get(fv)
        if not vs:
            continue
        deps_tools = vs.get("depends_on") or []
        used_prims = _classify_primitives(deps_tools)
        for p in used_prims:
            m.append(f"  {pv_node(p)} --> {_slug(fv)}")
    m.append("")
    m.append("```")

    # Primitive table
    rows = []
    for p in PRIMITIVES:
        impacted = primitive_to_skills.get(p.key) or []
        rows.append(
            {
                "primitive": p.label,
                "providers": ", ".join(p.providers),
                "skills_count": len(impacted),
                "skills": impacted,
            }
        )

    md = []
    md.append("# FinSkills 数据血缘（China-market）\n")
    md.append("本文件基于 `docs/view-deps.json` + `docs/view-specs/` 自动生成，用于评估数据源替换/缺失的影响范围。\n")
    md.append("## 总览图（Providers → Primitive Views → Feature Views）\n")
    md.extend([line + "\n" for line in m])
    md.append("\n## Primitive Views 影响面\n")
    md.append("| Primitive View | 可选提供方（akshare-one/AKShare） | 受影响 skills 数 | skills |\n")
    md.append("| --- | --- | ---: | --- |\n")
    for r in rows:
        skills = ", ".join(r["skills"][:18]) + (" ..." if len(r["skills"]) > 18 else "")
        md.append(f"| {r['primitive']} | {r['providers']} | {r['skills_count']} | {skills} |\n")

    md.append("\n## 备注\n")
    md.append("- `eastmoney/eastmoney_direct/sina/xueqiu` 的多提供方能力来自 akshare-one 的 `source` 参数设计。\n")
    md.append("- 其余标注为 `site-specific` 的 primitive 当前对应的是 AKShare 的站点级接口集合：可替换性通常取决于你是否有备选数据供应商或自建采集。\n")

    OUT_MD.parent.mkdir(parents=True, exist_ok=True)
    OUT_MD.write_text("".join(md), encoding="utf-8")
    print(f"Wrote {OUT_MD}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
